### ISSUE TITLE
Hide roll badges

### ISSUE THREAD

**Issue by cpcodes** [sPOiDar/fvtt-module-hide-gm-rolls#11]
I'm not sure exactly what they are called, and they might be specific to Pathfinder 2e, but in addition to the roll formula on an attack roll, information about the modifiers is displayed in badges. In the image below, you can see that while the module hides the roll formula, the "BASE MODIFIER +5" and "DEXTERITY +0" "badges" are still displayed.

![image](https://user-images.githubusercontent.com/30065410/108929780-80043d00-75f9-11eb-9dbf-08f738021232.png)

This will likely require some system specific logic, so if it does, no big, but if it doesn't, or is fairly simple, it'd make the info hiding fully functional for PF2e.

**Comment by sPOiDar** [comment]
I've not seen this on any other systems, are these chips used only for modifiers? If so, I may be able to hide them simply enough.

**Comment by cpcodes** [comment]
I'm not sure. I think so - it's all I've ever seen them display. The only chips you might want to keep are the ones that indicate the attack penalty for subsequent attacks (the so called MAP, or Multiple Attack Penalty).

**Comment by pdf** [comment]
I don't know if thr's a sensible way to distinguish between them. Can you provide me the steps to make it display that (I haven't played PF2e)?

**Comment by sPOiDar** [comment]
I don't know if there's a sensible way to distinguish between them. Can you provide me the steps to make it display that (I haven't played PF2e)?

**Comment by cpcodes** [comment]
Actually, you can close this request - the devs of the PF2E system will be updating the system to automatically hide them on private rolls anyway. Thanks for looking into this.

**Comment by cpcodes** [comment]
Actually, nevermind, I just realized that the system devs will be fixing it so that the chips are hidden for hidden rolls, but since these are not hidden rolls we are talking about, this still needs to be done. There should be an HTML attribute that indicates the chip, so it might be pretty easy to just make a CSS change (either globally or just for that element). They will be adding another attribute to distinguish trait tags (like attribute bonus and proficiency) and non-trait tags (like MAP and I assume circumstance bonuses). I'll keep you updated when that goes live so I can send you a snippet of the HTML.

**Comment by sPOiDar** [comment]
That sounds great!

**Comment by Gossetjr** [comment]
![image](https://user-images.githubusercontent.com/80440244/112256586-6971f580-8c3a-11eb-9047-4194f8c61194.png)

I think this may be what you've been waiting for?

**Comment by sPOiDar** [comment]
I don't think that's what we're looking for.

**Comment by cpcodes** [comment]
I'm not sure what that feature changed, but it does not seem to be what we need. I am thinking that a simple short term solution might be to simply hide the span class "tag_alt" (or maybe the entire div class "tags", but only for attack rolls). It would hide the MAP tag and any other tags that might be desirable, but until they add distinguishing classes for different types of tags. For reference, this is the current format for an attack roll.
```
<li class="chat-message message flexcol " data-message-id="ZO5HkDZo5F379AN0">
    <header class="message-header flexrow">
        <h4 class="message-sender">Guard</h4>
        <span class="message-metadata">
            <time class="message-timestamp">23s ago</time>
            <a class="button message-delete"><i class="fas fa-trash"></i></a>
        </span>
        <span class="flavor-text"><strong>Strike: Mace</strong><div class="tags"><span class="tag tag_alt">Base Modifier +5</span><span class="tag tag_alt">Dexterity +0</span><span class="tag tag_alt">Multiple Attack Penalty -5</span></div></span>
    </header>
    <div class="message-content">
        <div class="dice-roll">
    <div class="dice-result">
        <div class="dice-formula">1d20</div>
        <div class="dice-tooltip">
    <section class="tooltip-part">
        <div class="dice">
            <header class="part-header flexrow">
                <span class="part-formula">1d20</span>
                <span class="part-total">5</span>
            </header>
            <ol class="dice-rolls">
                <li class="roll die d20">5</li>
            </ol>
        </div>
    </section>
</div>
        <h4 class="dice-total">5</h4>
    </div>
</div>
    </div>
</li>
```
Here is a damage roll - it has the same div class "tags", but the contained tags only have the "tag" class, not the "tag_alt" class.
```
<li class="chat-message message flexcol " data-message-id="SC92iCOShyCOcfrK">
    <header class="message-header flexrow">
        <h4 class="message-sender">Ophiuchus</h4>
        <span class="message-metadata">
            <time class="message-timestamp">3m ago</time>
            <a class="button message-delete"><i class="fas fa-trash"></i></a>
        </span>
        <span class="flavor-text"><b>Damage Roll: Mace</b> (Success)<div class="tags"><span class="tag">attack</span><span class="tag">Range</span><span class="tag">Shove</span></div><hr><div style="display:flex;flex-wrap:wrap"><span class="damage-tag damage-tag-base">Base 1d6 + 1 bludgeoning</span></div></span>
    </header>
    <div class="message-content">
        <div class="dice-roll">
        <div class="dice-result">
            <div class="dice-formula">1d6 + 1</div>
            <div class="dice-tooltip" style="display:none"><div class="damage-type bludgeoning"><h3 class="flexrow"><span>bludgeoning</span><i class="fa fa-hammer"></i></h3>
                <div class="dice">
                    <header class="part-header flexrow">
                        <span class="part-formula">1d6 + 1</span>
                        <span class="part-flavor">physical</span>
                        <span class="part-total">3</span>
                    </header>
                    <ol class="dice-rolls"><li class="roll die d6">2</li></ol>
                </div>
            </div></div><h4 class="dice-total"><span id="value">3</span></h4></div></div>
    </div>
<div style="display: flex; margin-top: 3px;"><button style="flex: 1 1 0;" title="Apply full damage to selected tokens."><i class="fas fa-user-minus"></i></button><button style="flex: 1 1 0;" title="Apply half damage to selected tokens."><i class="fas fa-user-shield"></i></button><button style="flex: 1 1 0;" title="Apply double damage to selected tokens."><i class="fas fa-user-injured"></i></button><button style="flex: 1 1 0;" class="dice-total-shield-btn" title="Toggle the shield block status of the selected tokens."><i class="fas fa-shield-alt"></i></button><button style="flex: 1 1 0;" title="Apply full healing to selected tokens."><i class="fas fa-user-plus"></i></button></div></li>
```

**Comment by drexl93** [comment]
I found that adding this snippet to sanitizeRoll did the trick:

`const PF2etags = html.find('div.tags');
		if (PF2etags) {
			PF2etags.remove();
		}`

I'll defer to the module author on if it might have any unforseen side effects, but for the moment it's working just fine.

**Comment by sPOiDar** [comment]
@drexl93 AIUI this will hide all tags, and tags are used for all sorts of purposes in PF2e, not just bonuses, etc. Ideally I'd like to be able to only hide tags with information we consider 'sensitive', but I still don't see an easy way of doing that, considering there doesn't seem to be a way to differentiate bewteen tags for things like bonuses, and any other tag.

**Comment by drexl93** [comment]
What kind of other information are you referring to? From what I can see, that set of tags appears reserved for bonuses and penalties from any source (and that info is really only relevant to the person rolling the dice, not other people looking at the result). Stuff like special abilities that proc on attacks have their own separate blurb that's already configured so only the owner of the actor can see.

**Comment by sPOiDar** [comment]
I'll have to look into it further - it's just slightly painful for me to test all the possible rolls, since I don't use the system regularly.

**Comment by drexl93** [comment]
Totally, I understand. And thank you for your efforts. I thought I'd just post on this issue so anyone else playing PF2e who wants to take advantage of your (amazing) module can use this hacky temp-fix if they really want to.

**Comment by sPOiDar** [comment]
So, looks like tags are used on item cards and similar stuff, so I don't want to hide those. I think I can find a selector that will only target attack/damage cards though, hopefully their CSS/layout doesn't change too often.

**Comment by sPOiDar** [comment]
New version v0.8.0 should be published shortly that resolves this. Please feel free to re-open if you have any issues.
