### ISSUE TITLE
Request: Compatibility with BetterRolls5E

### ISSUE THREAD

**Issue by MathewBissonnette** [sPOiDar/fvtt-module-hide-gm-rolls#12]
I run both Hide GM Rolls and BetterRolls5E. The rolls work great and everything works as intended, but the "Hide GM item card description" option doesn't work when both modules are enabled.

I submitted the [issue with BetterRolls5E](https://github.com/RedReign/FoundryVTT-BetterRolls5e/issues/282#issuecomment-858267547) and they suggested the fix might need to come from this end.

**Comment by sPOiDar** [comment]
I'll look into it, shouldn't be too hard to resolve, and I already have some code for dealing with BetterRolls differences.

**Comment by sPOiDar** [comment]
New build should be on its way out shortly.
