### ISSUE TITLE
Better Rolls for 5E incompatibility - NaN Damage

### ISSUE THREAD

**Issue by apoapostolov** [sPOiDar/fvtt-module-hide-gm-rolls#13]
When Better Rolls for 5E and Hide GM Rolls are both active, damage rolls via Better Rolls for 5E are seen as NaN by players, but perfectly fine by GM.

**Comment by pdf** [comment]
Sorry about that, that'll be because I added a feature to merge their split crit rolls - I must have overlooked something. I'll push out a fix shortly.

**Comment by sPOiDar** [comment]
Sorry about that, that'll be because I added a feature to merge their split crit rolls - I must have overlooked something. I'll push out a fix shortly.

**Comment by sPOiDar** [comment]
Fixed in v0.9.2

**Comment by apoapostolov** [comment]
Thank you!
