### ISSUE TITLE
Private roll still adds "unread" badge to chat tab briefly

### ISSUE THREAD

**Issue by Kerdude** [sPOiDar/fvtt-module-hide-gm-rolls#15]
GM makes private roll, the player chat tab shows the new message dot for about 3 seconds then it clears. 

![image](https://user-images.githubusercontent.com/77137657/125025550-16347f00-e040-11eb-9dfa-474b7cc004d5.png)

**Comment by sPOiDar** [comment]
I'm not sure there's a an easy method to avoid this. I'm going to mark this `wontfix` for now - unless I feel particularly adventurous one day, I don't plan to look into this in the near future.

**Comment by DarKDinDoN** [comment]
Same here
![image](https://user-images.githubusercontent.com/1687854/126038345-f8173b6c-6554-4752-b1ef-fd510bcc1eeb.png)

**Comment by sPOiDar** [comment]
This feature should be available in v0.11.0, please report any issues you find.
