### ISSUE TITLE
[Feature Request] Option to not sanitize criticals/fumbles

### ISSUE THREAD

**Issue by MarkeyMarke** [sPOiDar/fvtt-module-hide-gm-rolls#22]
In some game systems (like 5e), a critical always hits and a fumble always misses. In this case; there's no point in sanitizing as the players can easily deduce numbers from seeing an irregular hit/miss. Moreover, this is more work for the GM to explain if an attack crits or misses.

Could we provide an option in the module settings to **not** sanitize criticals/fumbles?

**Comment by sPOiDar** [comment]
Sorry, can you explain exactly what it is you would like to happen? You want to show roll formulas when there's a crit or fumble, or...?

**Comment by MarkeyMarke** [comment]
Yes; I would like to show formulas when there's a crit or fumble.

**Comment by sPOiDar** [comment]
Then, is there a reason to hide roll formulas at all?

**Comment by MarkeyMarke** [comment]
Yes! It only becomes pointless when an npc crits or fumbles; but otherwise I would like my players to still not know their stats immediately.

**Comment by sPOiDar** [comment]
How about an option to just not hide the crit/fumble colors, so you see the green/red when they occur instead of unmasking the whole thing?

**Comment by MarkeyMarke** [comment]
Yes, that would be a workaround. That said, as a nice to have, is it possible to keep the base damage and critical damage totals separated? Example: '5 + 13' doesn't turn into '18'?

**Comment by sPOiDar** [comment]
Wait, are you talking about Better Rolls? If so, there's already an option specifically to disable sanitizing BR crits.

**Comment by MarkeyMarke** [comment]
Oh! I missed that, sorry. That works great then. Is it still possible to also allow the crit/fumble colors to show?

**Comment by sPOiDar** [comment]
My recollection is that when BR crit sanitization is disabled, it shows colors, since they use their own styling (though I can't confirm that 100% right now), so adding the option would only apply to people who aren't using BR.

**Comment by MarkeyMarke** [comment]
Here are my current settings:

![image](https://user-images.githubusercontent.com/32396474/135943400-bcb24af3-22b6-4010-9fc3-976ab5a0f156.png)


GM point-of-view:

![image](https://user-images.githubusercontent.com/32396474/135943430-6832b3ae-e3e9-48c3-a59f-dce92d9a2173.png)


Player point-of-view:

![image](https://user-images.githubusercontent.com/32396474/135943448-54e0312a-8c5f-4cf0-a5ed-d4a1b7806490.png)

**Comment by sPOiDar** [comment]
Ah maybe it's only fails they use custom styling for, or maybe they've changed something - I know I had to write special handling for them. I'll try and sort out an option to disable crit sanization in general when I can allocate some time.

**Comment by MarkeyMarke** [comment]
At a quick glance, it seems that my case is actually a bug. I took a look at the source code and determined the probable root cause are these two lines:

https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/blob/eb258553be78c37d99fd03cb8a454468f1d8ec74/modules/hide_gm_rolls.js#L95

https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/blob/eb258553be78c37d99fd03cb8a454468f1d8ec74/modules/hide_gm_rolls.js#L97

It looks like the classes/html elements were getting removed before checking if the BR setting is true.  It might be fixed by moving lines 92-99 into this if block?

https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/blob/eb258553be78c37d99fd03cb8a454468f1d8ec74/modules/hide_gm_rolls.js#L100

**Comment by sPOiDar** [comment]
Gotcha, I wouldn't call this a bug per se, since the effect is that BR behaves exactly the same as core rolls - color indicators are removed in general if sanitization is enabled. So, probably working as expected, but not as you would prefer, and this feat request will sort it out.

**Comment by MarkeyMarke** [comment]
Ah; gotcha! Thanks (:

**Comment by sPOiDar** [comment]
This feature should be available in v0.11.0, please report any issues you find.
