### ISSUE TITLE
Replace Total with Natural 20 or Natural 1 when those rolls occur

### ISSUE THREAD

**Issue by CarlosFdez** [sPOiDar/fvtt-module-hide-gm-rolls#27]
Right now, the modifier can be deduced on a natural 20 or a natural 1, like in the following example (PF2e):

![image](https://user-images.githubusercontent.com/1286721/167763631-e9f9ed26-b95c-42ff-a28e-d1e83ec0548d.png)

It'd be nice to have an option (at least for pf2e and 5e) to replace the entire roll result with the die number (such as Natural 20) in cases where a natural 20 or a natural 1 is rolled. And perhaps in 2e, remove the "by +X" when this occurs (as in 2e the degree of success is what changes).

**Comment by sPOiDar** [comment]
Replacing the number with 20 on crit might be a bit weird, because the toon can roll e.g. 23 on one turn, and then roll a "20", but it's actually a higher number.

**Comment by CarlosFdez** [comment]
Not replace with "20", replace with "Natural 20" if possible. 20 alone would indeed be weird.

**Comment by sPOiDar** [comment]
I don't think there's a sensible way to do this that's system-agnostic, since various systems use entirely different dice and values.

**Comment by CarlosFdez** [comment]
Understood. While it'd benefit both pf2e and 5e to do that, there could be any other number of systems that it might not work for. So don't worry about it!
