### ISSUE TITLE
[Feature Request] Add Compatability with Damage Log

### ISSUE THREAD

**Issue by SirMotte** [sPOiDar/fvtt-module-hide-gm-rolls#34]
I'd like to request compatibility with the [Damage Log Module](https://github.com/cs96and/FoundryVTT-damage-log).
This may or may not be related to #2 .

Issue: Chat cards added by this module are seemingly not recognized by Hide GM Rolls.

I've already contacted the author of the module as well, [please see this post](https://github.com/cs96and/FoundryVTT-damage-log/issues/30).

If you could either give some insight into how compatibility could be added by the Author of Damage Log, or if you yourself could take a look would be highly appreciated.

Thank you for this wonderful module, makes DMing so much more convenient!

**Comment by sPOiDar** [comment]
Hey @SirMotte sorry for the delay, haven't had much time for personal projects this year. When you say that chat cards are not recognised, can you elaborate - ie, what did you expect to happen, and what happened instead?

**Comment by esheyw** [comment]
I just got this warning: ![](https://i.imgur.com/O0zcuJ6.png)
Nothing seems obviously broken though.

**Comment by SirMotte** [comment]
> Hey @SirMotte sorry for the delay, haven't had much time for personal projects this year. When you say that chat cards are not recognised, can you elaborate - ie, what did you expect to happen, and what happened instead?

Hey sPOiDar, thanks for replying. I no longer use damage log, since I have switched over to Midi Qol. It's Author has already implemented similar solutions and compatibility with this and the Quick Reveal Module.

Please see this post. https://gitlab.com/tposney/midi-qol/-/issues/1116

Unless you still want to support the module mentioned above, even though I won't use it anymore, I will close this thread for now.
Thank you!
