### ISSUE TITLE
[Feature Request] Compatibility with Ready Set Roll

### ISSUE THREAD

**Issue by friction1** [sPOiDar/fvtt-module-hide-gm-rolls#35]
This module used to be compatible with Better Rolls, but that module has been replaced with "Ready Set Roll". When using Ready Set Roll, the sanitize GM rolls check doesn't seem to do anything (you can still see DCs and the roll on public rolls, not just the total result). I'm running D&D 5e with the latest stable foundry version.

**Comment by sPOiDar** [comment]
Please try v0.15.0, it has initial support for Ready Set Roll 5e. Feel free to report any issues.
