### ISSUE TITLE
Sanitize RSR 5e Crit Damage merges incorrectly with multiple damage rolls

### ISSUE THREAD

**Issue by hwangeug** [sPOiDar/fvtt-module-hide-gm-rolls#39]
If a creature rolls a critical hit, and the "Sanitize Ready Set Roll 5e Crit Damage" option is enabled, the merged damage is displayed incorrectly in two ways:

1. Both damage values are identical
2. The damage values are equal to the first-rolled damage concatenated with itself

**Example**

GM View:
![image](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/assets/11950803/2e677232-601a-4d88-b46c-86946feee225)

Player View:
![image](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/assets/11950803/1e7590e5-5044-4fc8-923a-410b4270263e)

**Comment by sPOiDar** [comment]
Should be resolved in v0.15.3
