### ISSUE TITLE
V12 Support

### ISSUE THREAD

**Issue by Deladriendil** [sPOiDar/fvtt-module-hide-gm-rolls#43]
cannot currently install in Foundry V12. will this be supported on the V12 release?

**Comment by weepingminotaur** [comment]
Would love v12 support

**Comment by 117ksk** [comment]
+1

**Comment by thejoester** [comment]
I found that if I edit the module (in the module list, right-click and choose "edit") and set the maximum version to 12, it seems to work fine for me.

**Comment by carolinex** [comment]
I'd also like v12 support

**Comment by BlackBadger777** [comment]
I love using this module and would love for it to support v12 and DnD5e 3.3.1 as well.

**Comment by MagrothJ** [comment]
Thanks a bunch for the update. :)
