### ISSUE TITLE
Obfusicate Descriptions

### ISSUE THREAD

**Issue by Alexis-Grimm** [sPOiDar/fvtt-module-hide-gm-rolls#7]
I don't have a great memory as a DM and I kind of rely on being able to see the exact description of my creatures attacks and abilities when I use them in chat, like I know generally what they do but remembering numbers is hard. Also I use some importer tools that put some info in the descriptions that I don't really need but would tip the players off to modifiers and stuff, it would be a lot of effort to go through and sanitize them all. Is there any chance an option could be added that hides the description of gm rolls from players while still allowing the gm to see them, and I don't mean the vanilla thing that just collapses the description by default, I mean to actually prevent the players from seeing it.

**Comment by sPOiDar** [comment]
Seems like a good addition, thanks for the suggestion!

**Comment by sPOiDar** [comment]
@Alexis-Grimm you should see an option to enable this in the latest version, let me know if you have any issues with it.

**Comment by Alexis-Grimm** [comment]
Thanks! I'll definitely check that out, I'll be preparing for my next game tomorrow
