### ISSUE TITLE
Version 0.6.0 core functionality broken

### ISSUE THREAD

**Issue by sirrus233** [sPOiDar/fvtt-module-hide-gm-rolls#8]
Version 0.6.0 of this module doesn't seem to work. I have tried on FoundryVTT version 0.7.7, using the latest DnD5e and PF2 systems, with the "Hide Private GM Rolls" setting enabled, and in all cases, a chat card still appears for the players.

I have tested with no other modules installed, so I believe this must be broken.

**Comment by sPOiDar** [comment]
Whoops! Did some refactoring last update and accidentally dropped the call to this method, fixed in 0.6.1 that should be live soon.
