### ISSUE TITLE
Hide crit values in attack rolls

### ISSUE THREAD

**Issue by Alexis-Grimm** [sPOiDar/fvtt-module-hide-gm-rolls#9]
When an npc crits on an attack roll the player sees the absolute maximum the attack could be and can figure out the modifier from there if they know its a crit, I know that you already have it so that it hides the colors that normally show up, but the way better rolls works the players can tell when the attack roll is a crit, without the colors, because of the way damage is rolled. I was wondering if it was possible to have critical rolls on attacks to output just the word crit to players instead of the rolled number or something similar, since crits hit regardless of the value.

**Comment by sPOiDar** [comment]
Sorry for the lengthy delay getting to this. Could you explain this to me:

> the way better rolls works the players can tell when the attack roll is a crit, without the colors, because of the way damage is rolled

Would it be better just to hide whatever thing makes it obvious what the result is, rather than hiding the value entirely? I am open to either option.

**Comment by Alexis-Grimm** [comment]
Hello, no problem on the long wait, I was just thinking that since the value of a critical hit doesn't actually matter you could hide the value to players so they can't tell what the modifier is, and just display that it was a crit, another option would be to have crit rolls from better rolls merge their damage since when a roll crits the damage value will look like "10 Crit: 5" or something like that, so even with the hidden colors it's obvious that it crit.

**Comment by sPOiDar** [comment]
I think I prefer the second option, though I'm concerned that it might be a little brittle. I think I'll push an update to support that behaviour, behind an setting.

**Comment by sPOiDar** [comment]
Closed in 6a6d7686dc2625120cc0f4537a2f257f95462efe (I forgot to tag it in the commit). Available in v0.9.1 that should be published shortly.
